name: Mark Alumni Users

on:
  workflow_dispatch:
    inputs:
      year:
        description: 'Year to mark as alumni (optional, defaults to current year)'
        required: false
        type: string
  schedule:
    - cron: '0 0 1 6 *' # 1st June every year at 00:00 UTC

jobs:
  mark-alumni:
    runs-on: ubuntu-latest
    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install root dependencies
        run: npm install

      - name: Mark users as alumni
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          EMAIL_ID: ${{ secrets.EMAIL_ID }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          node scripts/markAlumniGithubAction.js "${{ github.event.inputs.year }}"